name: onmetal-image
on: ["push", "workflow_dispatch"]
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
    with:
      source: git+https://github.com/onmetal/onmetal-image
      debian_source: native
      git_filter: v[0-9\.]*$
      git_tag_match: v([0-9\-]*)
